### ISSUE TITLE
Blacklisted apps blank

### ISSUE THREAD

**Issue by matsarg** [Skittyblock/Sushi#3]
The blacklisted apps option doesn’t show anything

**Comment by matsarg** [comment]
![47CD88CE-1384-4DF9-B834-C006D75620C2](https://github.com/Skittyblock/Sushi/assets/43357938/93b7d291-e1af-4463-9b25-fc9734e53783)

**Comment by Skittyblock** [comment]
Did you respring after installing? What device, iOS version, and jailbreak are you on?

**Comment by matsarg** [comment]
Respring yes. Rebooted no. I rebooted now and the problem it’s gone.
Thank you

**Comment by Skittyblock** [comment]
Honestly rebooting shouldn't have done anything. Not sure what the issue was, but part of the tweak hooks SpringBoard to send the app list to the preference bundle, and maybe that didn't activate upon installation for some reason.
