### ISSUE TITLE
Sushi not found in settings

### ISSUE THREAD

**Issue by meowgoober** [Skittyblock/Sushi#4]
I am trying to configure sushi but it isn’t in settings nor the other packages. I’m on iOS 15 with dopeamine jailbreak

**Comment by Skittyblock** [comment]
Did you try fully closing and reopening settings? It's just a regular preference bundle like any other tweak.

**Comment by meowgoober** [comment]
Yes. a lot of times

**Comment by Skittyblock** [comment]
Does the preference bundle exist in `(/var/jb)/Library/PreferenceBundles/Sushi.bundle`? I can't imagine why it wouldn't show up unless there's something conflicting, you don't have preferenceloader installed, or something messed up during installation.

**Comment by meowgoober** [comment]
Never mind. zebra didnt install prefrenceloader
